### ISSUE TITLE
[Styled-Component] 스타일 코드 수정 사항 공유 -(1)

### ISSUE THREAD

**Issue by damilog** [swing-park/sidedish#13]
스타일 코드 작성 중 수정한 사항에 대해 공유 드립니다.🙂

- `commonStyles.jsx` 내 `CardNPrice`와 `CardSPrice` 네이밍이 반대로 되어있어 이 부분 수정 하였습니다. 

-  Style reset을 위해 Styled-Component의 'styled-reset' 패키지를 설치 하였으며 `GlobalStyles.js` 내에 reset을 위한 스타일 코드를 작성하였습니다. `${reset}` 하단에 있는 태그들에 리셋과 관련된 코드를 자유롭게 작성 가능하오니 수정시 참고 바랍니다. (App.js에서 적용중인 컴포넌트 4개 모두 좌우 같은 padding값을 가지고 있어서 이 부분을 body 에 적용해도 괜찮을 것 같습니다~ )
- Style 속성 통일을 위하여 스타일 컴포넌트의 ThemeProvider 를 import 하였으며 해당 theme은 theme.js 에서 확인 가능합니다. 이 부분은 추후 스타일 코드 리팩토링 단계에서 중복 코드 삭제하는 과정에서 활용해보면 좋을 것 같습니다~!
- badge 스타일 일부 수정! badge내 텍스트가 두 줄로 나와 피그마를 참고하여 수정했습니다.
-  CardS/NPrice 은 한 줄로 나와야 하기에 div -> span 수정하였습니다.

**Comment by swing-park** [comment]
확인했습니다 !
